---
title: "Ticketing per direction demo"
author: "Eglantine Schmitt"
date: "04/04/2020"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr)
library(dplyr)
library(ggplot2)
source("../auth.R", chdir = T)
group = "lorient"
env = "staging"
```

# Log in

```{r}
sessionId = getSessionId(login_route, 
                         auth_route, 
                         credentials)
```

# Retrieve referential information and ticketing data

```{r}
lines = getResponseFromRoute(api_url,
                             sessionId,
                             "/rest/lines")

ticketing_raw_data = getResponseFromRoute(api_url,
                                          sessionId,
                                          "/kpis/ticketing/agency/17/line?aggregated_by_time=false&included_date_perimeters=2020-03-26_2020-04-02_1111111&excluded_date_perimeters=&ticket_type_id=all")
```

# Format and transform data

```{r}
referential_lines = do.call(rbind.data.frame, c(lines, stringsAsFactors = F))
ticketing_data = do.call(rbind.data.frame, c(ticketing_raw_data$data, stringsAsFactors = F))

ticketing_data = merge(x = ticketing_data, 
                       y = referential_lines,
                       by.x = "aggregation_level_id", 
                       by.y = "id")

lines_colours = unique(ticketing_data$colour)
names(lines_colours) = unique(ticketing_data$name)

ticketing_per_line = 
  ticketing_data %>%
  group_by(name) %>%
  summarise(direction_in = sum(direction_in))

head(ticketing_per_line)
```

# Visualise

```{r, echo= F}
  ggplot(ticketing_per_line, 
         aes(x= reorder(name, direction_in), 
             y=direction_in, 
             fill=name,
             label=direction_in)) + 
  geom_bar(stat="identity") +
  ggtitle (paste0("Nombre de validations par ligne (",
                  group,
                  ", du ",
                  min(ticketing_data$date),
                  " au ",
                  max(ticketing_data$date),
                  ")")) +
  ylab("Nombre de validations") +
  xlab(element_blank()) +
  scale_fill_manual(values=lines_colours)+ 
  theme_minimal()+
  theme(legend.position = "none")+
  #  geom_text(aes(label=direction_in), position = position_stack(vjust = 0.95),color = "white") +
  coord_flip()
```
